version: "3.7"

services:

  imdb_ratings_db:
    container_name: "imdb_ratings_db"
    image: postgres
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    shm_size: '512m'
    restart: always
    networks:
      - db_network
    volumes:
      - pgdata_volume:/var/lib/postgresql/data/

  imdb_ratings_redis:
    container_name: "imdb_ratings_redis"
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis_network
    volumes:
      - redis_volume:/data
    restart: always

  imdb_ratings_flask:
    container_name: imdb_ratings_flask
    env_file: .env
    build: ./flask
    image: imdb_ratings_flask
    restart: always
    expose:
      - 8080
    networks:
      - nginx_network
      - db_network
      - redis_network
    volumes:
      - ./flask:/code
    depends_on:
      - imdb_ratings_db
      - imdb_ratings_redis

  imdb_ratings_nginx:
    build: ./nginx
    container_name: imdb_ratings_nginx
    restart: always
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.metamovies_nginx-https.rule=Host("$VIRTUAL_HOST")'
      - 'traefik.http.routers.metamovies_nginx-https.tls.certresolver=httpchallenge_0'
      - 'traefik.http.routers.metamovies_nginx-http.rule=Host("$VIRTUAL_HOST")'
    networks:
      - nginx_network
      - traefik_network
    volumes:
      - ./nginx:/code
    depends_on:
      - imdb_ratings_flask

  imdb_ratings_celery:
    container_name: imdb_ratings_celery
    image: imdb_ratings_flask
    env_file: .env
    command: celery -A celery_init worker -l info -B
    restart: always
    networks:
      - db_network
      - redis_network
    volumes:
      - ./flask:/code
    depends_on:
      - imdb_ratings_db
      - imdb_ratings_redis
      - imdb_ratings_flask

  # imdb_ratings_celery-beat:
  #   container_name: imdb_ratings_celery-beat
  #   image: imdb_ratings_flask
  #   env_file: .env
  #   command: celery -A celery_init beat -l info
  #   restart: always
  #   networks:
  #     - db_network
  #     - redis_network
  #   volumes:
  #     - ./flask:/code
  #   depends_on:
  #     - imdb_ratings_db
  #     - imdb_ratings_redis
  #     - imdb_ratings_flask

networks:
  traefik_network:
    external:
      name: traefik_network
  db_network:
    driver: bridge
  redis_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  pgdata_volume:
  redis_volume:
  static_volume:
